---
title: "Data & Analysis"
author: "Verooo"
date: "2024-11-25"
output: html_document
bibliography: references.bib
csl: apa.csl
editor_options: 
  markdown: 
    wrap: 72
---

<html lang="en">

<head>

<meta charset="UTF-8">

<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>My Models</title>

<link rel="stylesheet" href="styles.css">
<!-- Link to the CSS file I created for dark mode code chunks -->

</head>

</html>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()

colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```


This work? 