---
title: "Week2 - Descriptives"
author: "Veroooo"
date: "2024-09-10"
output: html_document
---

```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```


```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```


```{r}
# install.packages("igraph")
library(igraph)
#install.packages("sna")
library(sna)


# Create a 4x4 matrix filled with 0's
matrix_zeros <- matrix(0, nrow = 4, ncol = 4)

# Add a tie between node 1 and node 3 by placing a 1
matrix_zeros[1, 3] <- 1  # From node 1 to node 3


# Print the matrix
print(matrix_zeros)

matrix_graph <- graph.adjacency(matrix_zeros)
sna::triad.census(matrix_zeros)

# output shows the count of each of the 16 possible configurations of triads  
    # so if below 003 it says e.g. 2, that means that the configuration 003 (A,B,C, the empty graph) is possible 2 times 


```


```{r}
# 003
# A,B,C, the empty graph.

# 012
# A->B, C, the graph with a single directed edge.

# 102
# A<->B, C, the graph with a mutual connection between two vertices.

# 021D
# A<-B->C, the out-star.

# 021U
# A->B<-C, the in-star.

# 021C
# A->B->C, directed line.

# 111D
# A<->B<-C.

# 111U
# A<->B->C.

# 030T
# A->B<-C, A->C.

# 030C
# A<-B<-C, A->C.

# 201
# A<->B<->C.

# 120D
# A<-B->C, A<->C.

# 120U
# A->B<-C, A<->C.

# 120C
# A->B->C, A<->C.

# 210
# A->B<->C, A<->C.

# 300
# A<->B<->C, A<->C, the complete graph.

```



```{r}
# install.packages("RSiena")
library(RSiena)
#install.packages("igraph")
# library(igraph)
#install.packages("sna")
library(sna)

?s501 # Network 1 data: excerpt from "Teenage Friends and Lifestyle Study" data.
dim(s501) # get dimensions of data

tenxten <- s501[1:10,1:10] # select a 10 x 10 matrix [rows and columns are divided by comma])

tenxten_graph <- graph.adjacency(tenxten) # make matrixa graph object 
plot(tenxten_graph) # make plot of network 


# assignment: give (on ego level) descriptive statistics on all kind of centrality measures 





```

