---
title: "week3 - class RSelenium"
author: "Verooo"
date: "2024-09-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---

```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

# see: https://jochemtolsma.github.io/webscraping/12scholars.html#13_necessary_packages
```{r}
# start with clean workspace
rm(list = ls())

# install.packages("RSelenium")
library(RSelenium)

# Web Driving with R Silenium 

```
# citing openalexR in paper!
If you use openalexR in research, please cite: (Priem, Piwowar, and Orr 2022)
